# Site settings
title: Laowang Blog
SEOTitle: 老王的博客 | Laowang Blog
header-img: img/home-bg.jpg
email: laowang@gmail.com
description: "这里是 @laowang 的个人博客，与你一起发现更大的世界 | 网络世界和平维护者，Serve The People"
keyword: "Laowang, Laowang老王, Lw, lw0x0, lw0x0, @lw0x0, 老王的博客, Laowang Blog, 博客, 个人网站, 互联网, Web, 安全, 渗透测试, 网络攻防, 威胁情报,安全技术"
url: "https://12379.net" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: huxpro
zhihu_username: huxpro
github_username: huxpro
twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "网络世界和平维护者，Serve The People <br> Xinian Team @ Laowang"
sidebar-avatar: https://github.com/xinian-66/xinian-66.github.io/blob/master/img/wrmfw.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
威胁情报:
  [
    { title: "安恒星图", href: "https://starmap.dbappsecurity.com.cn/" },
    { title: "VenusEye威胁情报中心", href: "https://www.venuseye.com.cn/" },
    { title: "NTI-威胁情报中心", href: "https://ti.nsfocus.com/" },
    { title: "奇安信威胁情报中心", href: "https://ti.qianxin.com/" },
    { title: "360安全大脑", href: "https://ti.360.cn/" },
    { title: "微步在线", href: "https://x.threatbook.com/" },
    { title: "RedQueen威胁情报中心", href: "https://redqueen.tj-un.com/IntelHome.html" },
    { title: "安天-威胁情报中心", href: "https://www.antiycloud.com/" },
  ]
